---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: config-route
spec:
  entryPoints:
  {{- if or .Values.ingress.ssl_enabled .Values.ingress.tls_resolver }}
    - websecure
  {{- end }}
  {{- if or .Values.ingress.tls_resolver (not .Values.ingress.ssl_enabled) }}
    - web
  {{- end }}
  routes:
  - match: 'Host(`{{ include "render-external-subdomain" (dict "service_name" "config" "Values" .Values) }}`)'
    kind: Rule
    services:
    - name: config
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.config.port }}
    middlewares:
      - name: sts-and-basic-response-headers
  {{- if .Values.ingress.tls_resolver }}
  tls:
    certResolver: {{ .Values.ingress.tls_resolver }}
  {{- else if .Values.ingress.tls_secret_name }}
  tls:
    secretName: {{ .Values.ingress.tls_secret_name }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config
    service_name: opencrvs_config
  name: config
spec:
  replicas: {{ .Values.config.replicas | default 1 }}
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      annotations:
        lastdeploy-timestamp: {{ now | quote }}
      labels:
        app: config
        service_name: opencrvs_config
    spec:
      {{- include "opencrvs.imagePullSecrets" (dict "root" . "service" .Values.config) | nindent 6 }}
      containers:
        - name: config
          image: {{ include "opencrvs.image" (dict "root" . "service" .Values.config) }}
          env:
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: FHIR_URL
              value: http://hearth.{{ .Release.Namespace }}.svc.cluster.local:3447/fhir
            - name: CLIENT_APP_URL
              value: {{ include "render-external-url" (dict "service_name" "register" "Values" .Values) }}
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "{{ .Values.config.port }}"
            - name: AUTH_URL
              value: "http://auth.{{ .Release.Namespace }}.svc.cluster.local:4040"
            - name: COUNTRY_CONFIG_URL
              value: http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040
            - name: COUNTRY_CONFIG_URL_INTERNAL
              value: http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040
            - name: USER_MANAGEMENT_URL
              value: http://user-mgnt.{{ .Release.Namespace }}.svc.cluster.local:3030/
          {{- if eq .Values.mongodb.auth_mode "disabled" }}     
            - name: HEARTH_MONGO_URL
              value: "mongodb://{{ .Values.mongodb.host }}/hearth-dev"
            - name: MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/application-config
          {{- else if or (eq .Values.mongodb.auth_mode "auto")  (eq .Values.mongodb.auth_mode "use_secret") }}
            - name: HEARTH_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: HEARTH_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: CONFIG_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
          {{- end }}
          {{- include "render-env-vars" (dict "service_name" "config" "Values" .Values) }}
          {{- include "resources-helper" (dict "service_name" "config" "Values" .Values) | indent 10 }}
          {{- include "probes-helper" (dict "service_name" "config" "Values" .Values) | indent 10 }}
          ports:
            - containerPort: {{ .Values.config.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: {{ .Release.Name }}-cert-tls
          name: public-key

{{- include "service-helper" (dict "service_name" "config" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "config" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "config" "Values" .Values) }}
