---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hearth
  name: hearth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hearth
  template:
    metadata:
      labels:
        app: hearth
    spec:
      {{- include "opencrvs.imagePullSecrets" (dict "root" . "service" .Values.hearth) | nindent 6 }}
      containers:
        - env:
            - name: authentication__type
              value: disabled
            - name: idGenerator
              value: uuidv4
            - name: logger__level
              value: warn
          {{- if eq .Values.mongodb.auth_mode "disabled" }}
            - name: mongodb__url
              value: mongodb://{{ .Values.mongodb.host }}/hearth-dev
          {{- else if or (eq .Values.mongodb.auth_mode "auto")  (eq .Values.mongodb.auth_mode "use_secret") }}
            - name: mongodb__url
              valueFrom:
                secretKeyRef:
                  key: HEARTH_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
          {{- end }}
            - name: server__fhirVersion
              value: stu3
          {{- if or .Values.hearth.secrets .Values.hearth.env .Values.env }}
          {{- include "render-env-vars" (dict "service_name" "hearth" "Values" .Values) }}
          {{- end }}
          image: {{ include "opencrvs.image" (dict "root" . "service" .Values.hearth) }}
          name: hearth
          ports:
            - containerPort: {{ .Values.hearth.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /fhir/Location?_count=1
              port: {{ .Values.hearth.port }}
          readinessProbe:
            httpGet:
              path: /fhir/Location?_count=1
              port: {{ .Values.hearth.port }}
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: hearth-cm-public-key
              subPath: public-key.pem
            - mountPath: /src/hearth/lib/plugins/checkDuplicateTask.js
              name: hearth-cm-checkduplicetask
              subPath: checkDuplicateTask.js
            - mountPath: /src/hearth/config/queryparam-extensions.json
              name: hearth-cm-queryparam-extensions
              subPath: queryparam-extensions.json
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: hearth-cm-public-key
          name: hearth-cm-public-key
        - configMap:
            items:
              - key: checkDuplicateTask.js
                path: checkDuplicateTask.js
            name: hearth-cm-checkduplicetask
          name: hearth-cm-checkduplicetask
        - configMap:
            items:
              - key: hearth-queryparam-extensions.json
                path: queryparam-extensions.json
            name: hearth-cm-queryparam-extensions
          name: hearth-cm-queryparam-extensions

{{- include "service-helper" (dict "service_name" "hearth" "Values" .Values) }}