---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics
  name: metrics
spec:
  replicas:  {{ .Values.metrics.replicas | default 1 }}
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      annotations:
        lastdeploy-timestamp: {{ now | quote }}
      labels:
        app: metrics
    spec:
      {{- include "opencrvs.imagePullSecrets" (dict "root" . "service" .Values.metrics) | nindent 6 }}
      containers:
        - image: {{ include "opencrvs.image" (dict "root" . "service" .Values.metrics) }}
          name: metrics
          env:
            - name: APN_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FHIR_URL
              value: http://hearth.{{ .Release.Namespace }}.svc.cluster.local:3447/fhir
            - name: METRICS_PORT  # Similar to PORT (Check if it's the same?)
              value: "1050"
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: CONFIG_API_URL
              value: http://config.{{ .Release.Namespace }}.svc.cluster.local:2021
            - name: COUNTRY_CONFIG_URL
              value: http://countryconfig.{{ .Release.Namespace }}.svc.cluster.local:3040
            - name: DOCUMENTS_URL
              value: http://documents.{{ .Release.Namespace }}.svc.cluster.local:9050
            - name: SEARCH_URL
              value: http://search.{{ .Release.Namespace }}.svc.cluster.local:9090/
            - name: USER_MANAGEMENT_URL
              value: http://user-mgnt.{{ .Release.Namespace }}.svc.cluster.local:3030
            - name: INFLUX_DB
              value: {{ .Values.influxdb.db | quote }}
            - name: INFLUX_HOST
              value: {{ .Values.influxdb.host | quote }}
            - name: INFLUX_PORT
              value: {{ .Values.influxdb.port | quote }}
          {{- if eq .Values.mongodb.auth_mode "disabled" }}
            - name: DASHBOARD_MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/performance
            - name: HEARTH_MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/hearth-dev
            - name: MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/metrics
          {{- else if or (eq .Values.mongodb.auth_mode "auto")  (eq .Values.mongodb.auth_mode "use_secret") }}
            - name: DASHBOARD_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: METRICS_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
            - name: HEARTH_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: HEARTH_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: METRICS_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
          {{- end }}
          {{- include "render-env-vars" (dict "service_name" "metrics" "Values" .Values) }}
          {{- include "resources-helper" (dict "service_name" "metrics" "Values" .Values) | indent 10 }}
          {{- include "probes-helper" (dict "service_name" "metrics" "Values" .Values) | indent 10 }}
          ports:
            - containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: {{ .Release.Name }}-cert-tls
          name: public-key

{{- include "service-helper" (dict "service_name" "metrics" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "metrics" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "metrics" "Values" .Values) }}
