{{- range $roleName, $roleCfg := .Values.postgres.roles }}

{{- $secretName := $roleCfg.secretName }}
{{- $existing := lookup "v1" "Secret" $.Release.Namespace $secretName }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
data:
  {{- if $existing }}
  # reuse existing values
  {{ $roleCfg.usernameKey | default "username" }}: {{ index $existing.data ($roleCfg.usernameKey | default "username") }}
  {{ $roleCfg.passwordKey | default "password" }}: {{ index $existing.data ($roleCfg.passwordKey | default "password") }}
  {{- else }}
  # generate new
  {{ $roleCfg.usernameKey | default "username" }}: {{ $roleName | b64enc }}
  {{ $roleCfg.passwordKey | default "password" }}: {{ randAlphaNum 32 | b64enc }}
  {{- end }}

---
{{- end }}