# FIXME: Refactor to k8s cronjobs, this is essentially a cron wrapper
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      {{- include "opencrvs.imagePullSecrets" (dict "root" . "service" .Values.scheduler) | nindent 6 }}
      containers:
        - name: scheduler
          image: {{ include "opencrvs.image" (dict "root" . "service" .Values.scheduler) }}
          env:
            - name: METRICS_URL
              value: http://metrics.{{ .Release.Namespace }}.svc.cluster.local:1050
          {{- if eq .Values.mongodb.auth_mode "disabled" }}
            - name: OPENHIM_MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/openhim-dev
          {{- else if or (eq .Values.mongodb.auth_mode "auto")  (eq .Values.mongodb.auth_mode "use_secret") }}
            - name: OPENHIM_MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: OPENHIM_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
          {{- end }}
          {{- include "render-env-vars" (dict "service_name" "scheduler" "Values" .Values) }}
      restartPolicy: Always
