---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search
    service_name: opencrvs_search
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      annotations:
        lastdeploy-timestamp: {{ now | quote }}
      labels:
        app: search
        service_name: opencrvs_search
    spec:
      containers:
        - name: search
          image: "ghcr.io/opencrvs/ocrvs-search:{{ .Values.image.tag }}"
          env:
            - name: APN_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: APPLICATION_CONFIG_URL
              value: http://config.{{ .Release.Namespace }}.svc.cluster.local:2021
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
          {{- if eq .Values.elasticsearch.auth_mode "disabled" }}
            - name: ES_HOST
              value: "{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
          {{- else if or (eq .Values.elasticsearch.auth_mode "auto") (eq .Values.elasticsearch.auth_mode "use_secret") }}
            - name: ES_HOST
              valueFrom:
                secretKeyRef:
                  key: SEARCH_ELASTIC_HOST
                  name: {{ .Values.elasticsearch.urls_secret }}
          {{- end }}
            - name: USER_MANAGEMENT_URL
              value: http://user-mgnt.{{ .Release.Namespace }}.svc.cluster.local:3030/
          {{- include "render-env-vars" (dict "service_name" "search" "Values" .Values) }}
          {{- include "resources-helper" (dict "service_name" "search" "Values" .Values) | indent 10 }}
          {{- include "probes-helper" (dict "service_name" "search" "Values" .Values) | indent 10 }}
          ports:
            - containerPort: {{ .Values.search.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: {{ .Release.Name }}-cert-tls
          name: public-key

{{- include "service-helper" (dict "service_name" "search" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "search" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "search" "Values" .Values) }}
