{{- if eq .Values.ingress.mode "traefik" }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webhooks-route
spec:
  entryPoints:
  {{- if or .Values.ingress.ssl_enabled .Values.ingress.tls_resolver }}
    - websecure
  {{- end }}
  {{- if or .Values.ingress.tls_resolver (not .Values.ingress.ssl_enabled) }}
    - web
  {{- end }}
  routes:
  - match: 'Host(`webhooks.{{ .Values.hostname }}`)'
    kind: Rule
    services:
    - name: webhooks
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.webhooks.port }}
    middlewares:
      - name: sts-and-basic-response-headers
  {{- if .Values.ingress.tls_resolver }}
  tls:
    certResolver: {{ .Values.ingress.tls_resolver }}
  {{- else if .Values.ingress.tls_secret_name }}
  tls:
    secretName: {{ .Values.ingress.tls_secret_name }}
  {{- end }}
{{- else }}
{{- include "ingress-helper" (dict "service_name" "dashboards" "Values" .Values) }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webhooks
    service_name: opencrvs_webhooks
  name: webhooks
spec:
  replicas: {{ .Values.webhooks.replicas | default 1 }}
  selector:
    matchLabels:
      app: webhooks
  template:
    metadata:
      labels:
        app: webhooks
        service_name: opencrvs_webhooks
    spec:
      containers:
        - name: webhooks
          image: "ghcr.io/opencrvs/ocrvs-webhooks:{{ .Values.image.tag }}"
          env:
            - name: APN_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FHIR_URL
              value: http://hearth.{{ .Release.Namespace }}.svc.cluster.local:3447/fhir
            - name: REDIS_HOST
              value: {{ .Values.redis.host | quote }}
            - name: AUTH_URL
              value: http://auth.{{ .Release.Namespace }}.svc.cluster.local:4040
            - name: CERT_PUBLIC_KEY_PATH
              value: /secrets/public-key.pem
            - name: CERT_PRIVATE_KEY_PATH
              value: /secrets/private-key.pem
            - name: CHECK_INVALID_TOKEN
              value: "true"
            - name: HOST
              value: 0.0.0.0
            - name: USER_MANAGEMENT_URL
              value: http://user-mgnt.{{ .Release.Namespace }}.svc.cluster.local:3030/
          {{- if eq .Values.mongodb.auth_mode "disabled" }}
            - name: MONGO_URL
              value: mongodb://{{ .Values.mongodb.host }}/webhooks
          {{- else if or (eq .Values.mongodb.auth_mode "auto")  (eq .Values.mongodb.auth_mode "use_secret") }}
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  key: WEBHOOKS_MONGO_URL
                  name: {{ .Values.mongodb.urls_secret }}
          {{- end }}
          {{- if eq .Values.redis.auth_mode "use_secret" }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: WEBHOOKS_REDIS_PASSWORD
                  name: {{ .Values.redis.users_secret }}
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  key: WEBHOOKS_REDIS_USERNAME
                  name: {{ .Values.redis.users_secret }}
          {{- end }}
          {{- include "render-env-vars" (dict "service_name" "webhooks" "Values" .Values) }}
          {{- include "resources-helper" (dict "service_name" "webhooks" "Values" .Values) | indent 10 }}
          {{- include "probes-helper" (dict "service_name" "webhooks" "Values" .Values) | indent 10 }}
          ports:
            - containerPort: {{ .Values.webhooks.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /secrets/public-key.pem
              name: public-key
              subPath: public-key.pem
            - mountPath: /secrets/private-key.pem
              name: private-key
              subPath: private-key.pem
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: public-key.pem
                path: public-key.pem
            name: {{ .Release.Name }}-cert-tls
          name: public-key
        - secret:
            secretName: {{ .Release.Name }}-key-tls
          name: private-key

{{- include "service-helper" (dict "service_name" "webhooks" "Values" .Values) }}

{{- include "hpa-helper" (dict "service_name" "webhooks" "Values" .Values) }}

{{- include "pdb-helper" (dict "service_name" "webhooks" "Values" .Values) }}
