name: Release Helm Charts

on:
  workflow_dispatch: {}
  push:
    branches: ["develop"]
    paths:
      - charts/**  # Trigger when any chart changes
      - .github/workflows/publish-charts.yml  # Trigger when this workflow file changes
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Package helm charts
        run: |
          mkdir packages
          charts=$(ls -1 charts)
          for chart in $(ls -1 charts)
          do
            helm package charts/$chart --destination packages
          done
      - name: Publish helm charts
        env:
            GITHUB_TOKEN_REGISTRY: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN_REGISTRY | helm registry login ghcr.io --username ocrvs-bot --password-stdin
          for package in $(ls -1 packages)
          do
            helm push packages/$package oci://ghcr.io/opencrvs
          done
